### ISSUE TITLE
Restore the history from Ruby trunk

### ISSUE THREAD

**Issue by rhenium** [ruby/sdbm#1]
All the changes made in the Ruby tree are squashed into one commit da62419c9b31 currently.

It reminds me of https://github.com/ruby/tk/pull/3. Would it be possible to restore the commit history similarly? While I have not contributed code to ext/sdbm, the history greatly helps understanding the background in general.

FWIW, a simple git filter-branch like this (on the Ruby trunk tree) would work for sdbm, I think:

	git filter-branch --prune-empty --index-filter '
		git rm --cached -qr --ignore-unmatch . &&
		git reset -q $GIT_COMMIT -- ext/sdbm test/sdbm &&
		git rm --cached -qr --ignore-unmatch ext/sdbm/sdbm.gemspec ext/sdbm/depend ext/sdbm/MANIFEST ext/sdbm/.cvsignore
	'  -- HEAD

(I'm doing a similar thing in ruby/openssl[*])

[*]: https://github.com/ruby/openssl/blob/master/tool/sync-with-trunk

**Comment by hsbt** [comment]
@rhenium Thanks your help. I try to restore commit history with your instructions.

**Comment by hsbt** [comment]
Restored commit history from ruby trunk repository.

see https://github.com/ruby/sdbm/commits/master

Great thanks!

**Comment by rhenium** [comment]
@hsbt It looks much nicer now than before, thanks for your work!
